(2022-09-21 10:49:46) [DEBUG] [util_funcs.py] (configure_logger): Deleted log file at: 
	C:\Users\Joke\Desktop\Frugality\data\logs\core.app.log.
(2022-09-21 10:49:47) [DEBUG] [util_funcs.py] (configure_logger): Permission denied for log file at:
	C:\Users\Joke\Desktop\Frugality\data\logs\core.app.log
	(This might be due to Flask restarting in debug!)
(2022-09-21 10:49:52) [INFO] [app.py] (query): Current operation: Groceries
(2022-09-21 10:51:50) [DEBUG] [util_funcs.py].(configure_logger): Permission denied for log file at:
	C:\Users\Joke\Desktop\Frugality\data\logs\core.app.log
	(This might be due to Flask restarting in debug!)
(2022-09-21 10:52:00) [DEBUG] [util_funcs.py].configure_logger: Permission denied for log file at:
	C:\Users\Joke\Desktop\Frugality\data\logs\core.app.log
	(This might be due to Flask restarting in debug!)
(2022-09-21 10:52:17) [DEBUG] [util_funcs.py.configure_logger]: Permission denied for log file at:
	C:\Users\Joke\Desktop\Frugality\data\logs\core.app.log
	(This might be due to Flask restarting in debug!)
(2022-09-21 10:52:43) [DEBUG] [util_funcs.py] (configure_logger): Permission denied for log file at:
	C:\Users\Joke\Desktop\Frugality\data\logs\core.app.log
	(This might be due to Flask restarting in debug!)
(2022-09-21 10:53:55) [INFO] [app.py] (query): Current operation: Groceries
(2022-09-21 10:54:26) [DEBUG] [util_funcs.py] {configure_logger}: Permission denied for log file at:
	C:\Users\Joke\Desktop\Frugality\data\logs\core.app.log
	(This might be due to Flask restarting in debug!)
(2022-09-21 10:54:28) [INFO] [app.py] {query}: Current operation: Groceries
